M48
; DRILL file {KiCad 8.0.8-8.0.8-0~ubuntu24.04.1} date 2025-02-03T16:43:05+0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-02-03T16:43:05+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8-8.0.8-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.300
%
G90
G05
T1
X63.82Y-72.17
X96.84Y-124.24
X112.08Y-73.44
T2
X57.0Y-46.5
X83.0Y-118.25
M30
